import fileReadHandler from "./file-read-handler";
import { Operation } from "./types";

describe("day10/file-read-handler", () => {
  it("should read in strings and convert them to numbers", () => {
    const lines = [
      "addx 15",
      "addx -11",
      "addx 6",
      "addx -3",
      "addx 5",
      "addx -1",
      "addx -8",
      "addx 13",
      "addx 4",
      "noop",
      "addx -1",
      "addx 5",
      "addx -1",
      "addx 5",
      "addx -1",
      "addx 5",
      "addx -1",
      "addx 5",
      "addx -1",
      "addx -35",
      "addx 1",
      "addx 24",
      "addx -19",
      "addx 1",
      "addx 16",
      "addx -11",
      "noop",
      "noop",
      "addx 21",
      "addx -15",
      "noop",
      "noop",
      "addx -3",
      "addx 9",
      "addx 1",
      "addx -3",
      "addx 8",
      "addx 1",
      "addx 5",
      "noop",
      "noop",
      "noop",
      "noop",
      "noop",
      "addx -36",
      "noop",
      "addx 1",
      "addx 7",
      "noop",
      "noop",
      "noop",
      "addx 2",
      "addx 6",
      "noop",
      "noop",
      "noop",
      "noop",
      "noop",
      "addx 1",
      "noop",
      "noop",
      "addx 7",
      "addx 1",
      "noop",
      "addx -13",
      "addx 13",
      "addx 7",
      "noop",
      "addx 1",
      "addx -33",
      "noop",
      "noop",
      "noop",
      "addx 2",
      "noop",
      "noop",
      "noop",
      "addx 8",
      "noop",
      "addx -1",
      "addx 2",
      "addx 1",
      "noop",
      "addx 17",
      "addx -9",
      "addx 1",
      "addx 1",
      "addx -3",
      "addx 11",
      "noop",
      "noop",
      "addx 1",
      "noop",
      "addx 1",
      "noop",
      "noop",
      "addx -13",
      "addx -19",
      "addx 1",
      "addx 3",
      "addx 26",
      "addx -30",
      "addx 12",
      "addx -1",
      "addx 3",
      "addx 1",
      "noop",
      "noop",
      "noop",
      "addx -9",
      "addx 18",
      "addx 1",
      "addx 2",
      "noop",
      "noop",
      "addx 9",
      "noop",
      "noop",
      "noop",
      "addx -1",
      "addx 2",
      "addx -37",
      "addx 1",
      "addx 3",
      "noop",
      "addx 15",
      "addx -21",
      "addx 22",
      "addx -6",
      "addx 1",
      "noop",
      "addx 2",
      "addx 1",
      "noop",
      "addx -10",
      "noop",
      "noop",
      "addx 20",
      "addx 1",
      "addx 2",
      "addx 2",
      "addx -6",
      "addx -11",
      "noop",
      "noop",
      "noop",
    ];
    const accumulator = [];
    lines.forEach((line) => {
      fileReadHandler(accumulator, line);
    });
    expect(accumulator).toEqual([
      { operation: Operation.AddX, value: 15 },
      { operation: Operation.AddX, value: -11 },
      { operation: Operation.AddX, value: 6 },
      { operation: Operation.AddX, value: -3 },
      { operation: Operation.AddX, value: 5 },
      { operation: Operation.AddX, value: -1 },
      { operation: Operation.AddX, value: -8 },
      { operation: Operation.AddX, value: 13 },
      { operation: Operation.AddX, value: 4 },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: -1 },
      { operation: Operation.AddX, value: 5 },
      { operation: Operation.AddX, value: -1 },
      { operation: Operation.AddX, value: 5 },
      { operation: Operation.AddX, value: -1 },
      { operation: Operation.AddX, value: 5 },
      { operation: Operation.AddX, value: -1 },
      { operation: Operation.AddX, value: 5 },
      { operation: Operation.AddX, value: -1 },
      { operation: Operation.AddX, value: -35 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.AddX, value: 24 },
      { operation: Operation.AddX, value: -19 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.AddX, value: 16 },
      { operation: Operation.AddX, value: -11 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 21 },
      { operation: Operation.AddX, value: -15 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: -3 },
      { operation: Operation.AddX, value: 9 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.AddX, value: -3 },
      { operation: Operation.AddX, value: 8 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.AddX, value: 5 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: -36 },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.AddX, value: 7 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 2 },
      { operation: Operation.AddX, value: 6 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 7 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: -13 },
      { operation: Operation.AddX, value: 13 },
      { operation: Operation.AddX, value: 7 },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.AddX, value: -33 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 2 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 8 },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: -1 },
      { operation: Operation.AddX, value: 2 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 17 },
      { operation: Operation.AddX, value: -9 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.AddX, value: -3 },
      { operation: Operation.AddX, value: 11 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: -13 },
      { operation: Operation.AddX, value: -19 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.AddX, value: 3 },
      { operation: Operation.AddX, value: 26 },
      { operation: Operation.AddX, value: -30 },
      { operation: Operation.AddX, value: 12 },
      { operation: Operation.AddX, value: -1 },
      { operation: Operation.AddX, value: 3 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: -9 },
      { operation: Operation.AddX, value: 18 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.AddX, value: 2 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 9 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: -1 },
      { operation: Operation.AddX, value: 2 },
      { operation: Operation.AddX, value: -37 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.AddX, value: 3 },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 15 },
      { operation: Operation.AddX, value: -21 },
      { operation: Operation.AddX, value: 22 },
      { operation: Operation.AddX, value: -6 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 2 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: -10 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.AddX, value: 20 },
      { operation: Operation.AddX, value: 1 },
      { operation: Operation.AddX, value: 2 },
      { operation: Operation.AddX, value: 2 },
      { operation: Operation.AddX, value: -6 },
      { operation: Operation.AddX, value: -11 },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
      { operation: Operation.Noop },
    ]);
  });
});
